name: Create Release
on: 
  push:
    tags:
      - "v*.*.*"
      
jobs: 
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Import Terraform Registry GPG Key
        run: echo ${{ secrets.TERRAFORM_REGISTRY_GPG }} | gpg --import
      
      - name: Build Artifacts
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - run: bash build-for-terraform-registry.sh
